language: java
install: true
script: if [[ "$TRAVIS_REPO_SLUG" == "immutables/immutables" && "$TRAVIS_BRANCH" == "master" ]]; then mvn deploy -DdeployAtEnd=true --settings settings.xml; else mvn package; fi
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8

